raw_dataset_dir: data/raw/
interim_dataset_dir: data/interim/
processed_dataset_dir: data/processed/

# forests or pascal-voc
dataset: forests

image_size: 224
train_size: 0.8
shuffle: False
batch_size: 16

seed: 324
