name: Push notebook to kaggle

on:
  push:
    branches:
      - train

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Push Kaggle kernel
        run: kaggle kernels push -p kaggle/
  
      - name: Checking Kaggle Status
        run: |
          bash .github/workflows/checking_kaggle_status.sh $KAGGLE_KERNEL_ID
  
      - name: Download outputs
        run: |
          kaggle k output $KAGGLE_KERNEL_ID -p outputs/
          ls outputs/
